### ISSUE TITLE
Rotating Pointcloud 

### ISSUE THREAD

**Issue by ghost** [tum-gis/a2d2_ros_preparer#1]
First of all, great work and very well structured package. 

I just cloned the most recent code off of github and used it to convert "a2d2-preview/camera_lidar/20180810_150607" to a rosbag. The conversion executes as expected and produces a rosbag that I am able to visualize in rviz.

However there is a problem when the pointclouds are visualized, they look like they are rotating around the car. Do you have any thoughts on why this might be? 

If you have a second to think about this and need more information about the setup/problem please let me know. Cheers!

**Comment by benediktschwab** [comment]
Glad that the package helps you and that the camera streams are working. From next week on, I will have access to my laptop again.

Could you test setting the parameter 
`lidar_publish_period_sec` of the yaml config to 0.1 (revolution duration of one LiDAR) and rerun the conversion? The [launch file](https://github.com/tum-gis/a2d2_ros_preparer/blob/1b4a9e3c5a7c63d642770338bde3964a0e831d49/a2d2_ros_preparer/launch/convert.launch) references a yaml config with the conversion parameters. A default yaml can be found [here](https://github.com/tum-gis/a2d2_ros_preparer/blob/1b4a9e3c5a7c63d642770338bde3964a0e831d49/a2d2_ros_preparer/config/default.yaml).
Does this change the LiDAR visualization within rViz?

**Comment by ghost** [comment]
Setting the `lidar_publish_period_sec` to 1e-1 seems to solve the problem! Thanks for the tip, quick response, and great package!

**Comment by benediktschwab** [comment]
Great, maybe a little explanation: The LiDAR sensors of the A2D2 vehicle are rotating at a [speed of 10Hz](https://a2d2-ros-preparer.readthedocs.io/en/latest/dataset_preparation.html#sensor-speeds). Each reflection point has a timestamp in the original npz files.
The [PointCloud2 message](http://docs.ros.org/en/noetic/api/sensor_msgs/html/msg/PointCloud2.html) of ROS accumulates a list of points at a specific timestamp specified in the header.

Thus, the a2d2_ros_preparer accumulates a list of points into one ROS message and uses time frames with a duration of `lidar_publish_period_sec`. I hope this helps!
