### ISSUE TITLE
GetMinMaxMiddleTime always returns start time

### ISSUE THREAD

**Issue by markuspi** [tum-gis/a2d2_ros_preparer#2]
There is a typo in TimedPointCloudData::GetMinMaxMiddleTime that leads to the function always returning the start time instead of the mean between start and end. Line 70 is probably intended to be `auto max_time = GetStopTime();`. I don't know if and how this affects the result however

https://github.com/tum-gis/a2d2_ros_preparer/blob/970f0e6ef483e1c044c16bacd6f6bcba09ef62ca/a2d2_ros_preparer/src/lidar/timed_point_cloud_data.cpp#L68-L73

**Comment by benediktschwab** [comment]
Hi Markus,

thank you for noticing and reporting the bug. I just fixed it:
https://github.com/tum-gis/a2d2_ros_preparer/blob/724c12912aebc3e714b298f4dfe7126e23f4ff3f/a2d2_ros_preparer/src/lidar/timed_point_cloud_data.cpp#L68-L73

Please let me know if this change has some detrimental side effects in case you use this package.
